baseURL: /
languageCode: en-us
paginate: 6
theme: portio-hugo-data-science
title: Chris Pachulski's Data Science Portfolio
menu:
  main:
    - name: Home
      url: '#home'
      weight: 1
    - name: About
      url: '#about'
      weight: 2
    - name: Portfolio
      url: '#portfolio'
      weight: 4
    - name: Resume
      url: '#resume'
      weight: 5
    - name: Blog
      url: blog
      weight: 6
  sitemap:
    - name: Home
      url: /
      weight: 1
    - name: Blog
      url: blog
      weight: 2
params:
  blogPageURL: blog
  contactButtonLabel: Contact Chris Today
  contactLink: '#contact'
  copyright: All right reserved copyright © Chris Pachulski 2022
  footerLogo: images/site-navigation/logo.jpeg
  formspreeURL: YOUR FORMSPREE URL
  googleAnalytics: YOUR GOOGLE ANALYTICS CODE
  logo: images/site-navigation/logo.jpeg
  social:
    - icon: fa-linkedin-square
      url: https://www.linkedin.com/in/chris-pachulski/
      weight: 1
    - icon: fa-github
      url: https://github.com/ChrisPachulski/
      weight: 2
    - icon: fa-twitter-square
      url: https://twitter.com/WolfOfTinStreet
      weight: 3
    - icon: discord
      url: https://discord.com/channels/@me/442089307889467412
      weight: 4
