---
baseURL: "/"
languageCode: en-us
paginate: 6
theme: portio-hugo-data-science
title: Chris Pachulski's Data Analytics Portfolio
menu:
  main:
  - url: blog
    name: Blog
    weight: 5
  - url: "#portfolio"
    name: Portfolio
    weight: 3
  - url: "#resume"
    name: Resume
    weight: 4
  - url: "#about"
    name: About
    weight: 2
  - url: "#home"
    name: Home
    weight: 1
  sitemap:
  - url: blog
    name: Blog
    weight: 2
  - url: "/"
    name: Home
    weight: 1
params:
  blogPageURL: blog
  contactButtonLabel: Contact Chris Today
  contactLink: "#contact"
  copyright: All right reserved copyright © Chris Pachulski 2022
  footerLogo: images/site-navigation/logo.jpeg
  formspreeURL: https://formspree.io/f/xvoyaeyd
  googleAnalytics: YOUR GOOGLE ANALYTICS CODE
  logo: images/site-navigation/logo.jpeg
  social:
  - icon: fa-linkedin-square
    url: https://www.linkedin.com/in/chris-pachulski/
    weight: 1
  - icon: fa-github
    url: https://github.com/ChrisPachulski/
    weight: 2
  - icon: fa-twitter-square
    url: https://twitter.com/WolfOfTinStreet
    weight: 3
  - icon: fa-slack
    url: https://discord.com/channels/@me/442089307889467412
    weight: 4
